sources:
  include:
    - GPSchedule
  exclude:
    - GPSchedule/ApiClient/Generated/OpenMRS/Classes/Swaggers/APIs
    - GPSchedule/ApiClient/Generated/OpenMRS/Classes/Swaggers/Models.swift
templates:
- GPSchedule/Templates
#- <templates path>
output:
    path: GPSchedule/Generated
#args:
#<name>: <value>
