disabled_rules: # rule identifiers to exclude from running
  - todo
opt_in_rules: # some rules are only opt-in
  - empty_count
  - vertical_whitespace
  - force_unwrapping
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - let_var_whitespace
  - multiline_arguments
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - yoda_condition
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
#  - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - GPSchedule/ApiClient
  - GPSchedule/Generated
  - GPScheduleUnitTests

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 160
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
variable_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - url
    - app
    - lhs
    - rhs
    - day
    - for
    - end
    - key
    - to
    - tag
    - map
    - old
    - ids
    - all
    - top
    - raw
    - of
    - api
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)

