target 'GPSchedule' do
  use_frameworks!

  # Pods for GPSchedule
  pod 'RxSwift'
  pod 'RxSwiftExt'
  pod 'RxOptional'
  pod 'RxFeedback'

  pod 'Cartography'
  pod 'Bento', :git => 'https://github.com/Babylonpartners/Bento.git'
  pod 'BentoKit', :git => 'https://github.com/Babylonpartners/Bento.git'
  pod 'StyleSheets', :git => 'https://github.com/Babylonpartners/Bento.git'

  pod 'OpenMRS', :path => './GPSchedule/ApiClient/Generated/OpenMRS.podspec'

  pod 'Sourcery'
  pod 'SwiftLint'
end

target 'GPScheduleUnitTests' do
  use_frameworks!

  # Pods for GPScheduleUnitTests
  pod 'RxBlocking'
  pod 'RxTest'
  pod 'RxSwift'
  pod 'RxOptional'
  pod 'Quick'
  pod 'Nimble'
  pod 'Sourcery'
end
