# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPSchedule' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GPSchedule
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxSwiftExt'
  pod 'RxOptional'
  pod 'RxFeedback'

  pod 'Cartography'

  pod 'Sourcery'
end
