//
//  LogInViewController.swift
//  GPSchedule
//
//  Created by Jakub Tomanik on 08/03/2019.
//  Copyright © 2019 Jakub Tomanik. All rights reserved.
//

import Foundation
import UIKit
import RxSwift
import RxSwiftExt

// sourcery: store = "RootStore"
// sourcery: defaultState = "logIn"
class LoginViewModel: ViewReactor {

    enum State: ViewState {
        case logIn
        case loggedIn
        case loading
        case error(Error)

        enum UserAction {}
    }

    // sourcery:inline:ViewReactor.common
    // Autogenerated content below, do not modify
    let store: RootStore
    let action = PublishSubject<State.UserAction>()
    let state = BehaviorSubject<State>(value: .logIn)

    required init(store: RootStore) {
        self.store = store
    }
    
    // sourcery:end
}


// sourcery: viewmodel = "LoginViewModel"
class LoginViewController: UIViewController, AppView {

    // sourcery:inline:AppView.common
    // sourcery:end
}
